language: ruby
rvm:
  - 2.5.3

before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem update --system
  - gem install bundler

script:
  # - bundle install --jobs=3 --retry=3
  - bundle exec jekyll build
  # - bundle exec htmlproofer ./_site --allow_hash_href --disable-external

env:
  global:
    - JEKYLL_ENV=production
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache: bundler
