language: ruby
rvm:
  - 2.5.3

before_install:
  - gem update --system --no-document
  - gem install bundler --no-rdoc --no-ri

script:
  - bundle exec jekyll build
  # - bundle exec htmlproofer ./_site --allow_hash_href --disable-external

env:
  global:
    - JEKYLL_ENV=production
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache: bundler
