language: ruby
rvm:
  - 2.5.3

before_install:
  - gem update --system
  - gem install bundler --no-document

script:
  - bundle exec jekyll build
  # - bundle exec htmlproofer ./_site --disable-external

env:
  global:
    - JEKYLL_ENV=production
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache: bundler
