language: ruby
rvm:
  - 2.5.3
gem: --no-rdoc --no-ri

before_install:
  - gem update --system
  - gem install bundler

script:
  - bundle exec jekyll build
  # - bundle exec htmlproofer ./_site --allow_hash_href --disable-external

env:
  global:
    - JEKYLL_ENV=production
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache: bundler
