# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Colorado Adult Education Professional Association
description: | # Scalar content can be written in block notation, | Literal style , > Folded style
  Providing Colorado Leadership in Adult Education and Literacy since 1935.
  The Colorado Adult Education Professional Association, CAEPA, provides leadership to the field of adult education and family literacy by offering opportunities for professional development, advocacy, and resource sharing to improve the quality of life for every Coloradan.

url: http://news.caepa.org
repository: caepa/news.caepa.org

author: CAEPA
email: communications@caepa.org

google_analytics: UA-76548901-1
google_site_verification: 9aWiSPXxIMqz4XsA1BbxONHgHSSVeTczQFS0fJcgEZE

# social links
twitter_username: caepa_co
github_username:  caepa
facebook_username: caepa.co
# linkedin_username: caepa-co
linkedin_username: colorado-adult-education-professional-association-caepa- # currently inaccessible

# seo
twitter:
  username: caepa_co
facebook:
  app_id: 313577104485
  publisher: 313577104485
  admins: 776863769
social:
  name: CAEPA
  links:
    - https://www.facebook.com/caepa.co
    - http://github.com/caepa
    # - https://www.linkedin.com/company/caepa-co
    - https://www.linkedin.com/company/colorado-adult-education-professional-association-caepa- # currently inaccessible
    - https://twitter.com/caepa_co
    - http://news.caepa.org/feed.xml

# social media buttons
social_media:
  # - name: dropbox
  #   url:  http://dropbox.com
  # - name: google-plus
  #   url:  http://plus.google.com/caepaboard
  - name: facebook
    url:  https://www.facebook.com/caepa.co
  - name: github
    url:  http://github.com/caepa
  - name: linkedin
  #   url:  https://www.linkedin.com/company/caepa-co/
    url:  https://www.linkedin.com/company/colorado-adult-education-professional-association-caepa- # inaccessible
  - name: rss
    url:  http://news.caepa.org/feed.xml
  - name: twitter
    url:  https://twitter.com/caepa_co

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.


# Collections
collections_dir: collections


# Front matter defaults
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/caepa/icon.svg
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:title.html


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
feed:
  categories:
    - news
    - events
    - updates

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - package.json
  - README.md
  - staticman.yml
  - vendor
  - webpack.config.js
  - webpack.style-bundle.js
include:
  - _pages
sass:
  load_paths:
    - assets
  style: compressed


# reCaptcha (!) ENCRYPTED
reCaptcha:
  siteKey: "6Ld6x1EUAAAAACz3jturPJf2xDBa8jy-aZCxPzEW"
  secret: "B/l1AS3JUZPaAohFvCiNJkxU/YMy7psdeYJ9zQzpTia3IWXxqiQwA8tipSYeLBPJmbf4lSAYHydoDC0N5mkaeNZGEsTegWZssM+sr8sIf4t/U1rcBfnncqQZjLGNAxH7WpBFD05ckAJRXz8XOP7hSwOLJCYdcZ75U8rXCZHulb0="
